version: '3'
services:

  nginx:
    container_name: proxy
    image: nginx:latest
    networks:
      - routing_proxy
    ports:
      - "80:50000"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
    working_dir: /code
    restart: always

networks:
  routing_proxy:
    name: routing_proxy
