version: '3'
services:

  nginx:
    container_name: proxy
    image: nginx:latest
    networks:
        vps_proxy:
    ports:
      - "80:50000"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - ./../:/code
    restart: always

networks:
  vps_proxy:
    name: vps_proxy