version: '3'
services:

  nginx:
    container_name: proxy
    image: nginx:latest
    networks:
        routing_proxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/etc:/etc/letsencrypt
      - ./:/code
    working_dir: /code
    restart: always

networks:
  routing_proxy:
    name: routing_proxy